[package]
name         = "dev.peios.timed-debugsource"
architecture = "x86_64"
description  = "Debug sources for timed and clock"

[dependencies]
"dev.peios.timed-debuginfo" = "= {{version}}-1"
"dev.peios.clock-debuginfo" = "= {{version}}-1"

[files]
"@source:LICENSE"   = "usr/share/licenses/dev.peios.timed-debugsource/LICENSE"
":licenses/**"      = "usr/share/licenses/dev.peios.timed-debugsource/third-party"
":usr/src/debug/**" = "usr/src/debug"
